apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"labels":{"app.kubernetes.io/name":"httpd"},"name":"httpd","namespace":"default"},"spec":{"selector":{"matchLabels":{"app.kubernetes.io/name":"httpd"}},"template":{"metadata":{"labels":{"app.kubernetes.io/name":"httpd"}},"spec":{"containers":[{"env":[{"name":"PORT","value":"80"}],"image":"httpd:alpine","imagePullPolicy":"Always","name":"httpd","ports":[{"containerPort":80,"name":"http","protocol":"TCP"}],"readinessProbe":{"httpGet":{"path":"/","port":80},"initialDelaySeconds":10,"periodSeconds":10,"timeoutSeconds":2}}]}}}}
  creationTimestamp: "2023-10-12T12:15:32Z"
  generation: 4
  labels:
    app.kubernetes.io/name: httpd
  name: httpd
  namespace: default
  resourceVersion: "104063"
  uid: f249c9c7-4f96-4d71-9d68-3bcf0be322f3
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app.kubernetes.io/name: httpd
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: httpd
    spec:
      containers:
      - env:
        - name: PORT
          value: "80"
        image: httpd:alpine
        imagePullPolicy: Always
        name: httpd
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 80
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2023-10-12T12:15:32Z"
    lastUpdateTime: "2023-10-16T11:33:35Z"
    message: ReplicaSet "httpd-66bc64d6cd" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2023-10-16T12:12:34Z"
    lastUpdateTime: "2023-10-16T12:12:34Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 4
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
