apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-pv-httpd
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  hostPath:
    path: /data/my-pv-httpd
